# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 21a93c1f9243aa19f1ec12bfcfc1a3c47dea4a7fa30d77fefc6ed9bfc273115d596777e19ba679a6dd6031070614adb8f01b5b3edba12995a13f5b38a7b51fd3

test:
  secret_key_base: 2ffcd389ee00d4e673f759ef9dbd338fda9fa207693079e49cd1763a171f35a0b1498245b9730593fc21ee98f2626ec1a300436b3e028740d50dd3498e16b8b2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
